# Copyright (C) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license. See LICENSE.txt in the project root for license information.

variables:
  BuildConfiguration: Release

trigger: none

pr:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md

pool:
  vmImage: windows-2022


steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: '7.x'
    
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: 'VSConfigFinder'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: 'VSConfigFinder.Test'
    arguments: '--configuration $(BuildConfiguration)'