# Copyright (C) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license. See LICENSE.txt in the project root for license information.

parameters:
  BuildConfiguration: Release

steps:
- powershell: |
    dotnet tool install --tool-path "${env:AGENT_TOOLSDIRECTORY}\nbgv" nbgv
    $version = & "${env:AGENT_TOOLSDIRECTORY}\nbgv\nbgv.exe" get-version --variable SemVer1
    & "${env:AGENT_TOOLSDIRECTORY}\nbgv\nbgv.exe" cloud --version $version
  displayName: 'Set cloud build version'

- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    useGlobalJson: true
    
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: 'VSConfigFinder'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: 'VSConfigFinder.Test'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    arguments: '--no-build --configuration $(BuildConfiguration)'
    publishWebProjects: false
    zipAfterPublish: false

- script: |
    choco pack pkg\VSConfigFinder\VSConfigFinder.nuspec --out "VSConfigFinder\bin\${{ parameters.BuildConfiguration }}" --version "%NBGV_NuGetPackageVersion%" "Configuration=${{ parameters.BuildConfiguration }}" "CommitId=$(Build.SourceVersion)" "Tag=$(Build.BuildNumber)"
  displayName: Package
  workingDirectory: $(Build.SourcesDirectory)

- task: CopyFiles@2
  displayName: 'Copy build artifacts from: $(Build.SourcesDirectory)\VSConfigFinder\bin\$(BuildConfiguration)\** to $(Build.ArtifactStagingDirectory)\out'
  inputs:
    SourceFolder: $(Build.SourcesDirectory)\VSConfigFinder
    Contents: |
     bin\$(BuildConfiguration)\**
    TargetFolder: $(Build.ArtifactStagingDirectory)\out

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts from: $(Build.ArtifactStagingDirectory)\out'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)\out
    ArtifactName: drop
    publishLocation: Container