# Copyright (C) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license. See LICENSE.txt in the project root for license information.

variables:
  BuildConfiguration: Release

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md

pr: none

queue:
  name: VSEngSS-MicroBuild2019-1ES
  timeoutInMinutes: 120

steps:

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: 'VSConfigFinder'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: 'VSConfigFinder.Test'
    arguments: '--configuration $(BuildConfiguration)'

- task: CopyFiles@2
  displayName: Copy build artifacts
  inputs:
    SourceFolder: $(Build.SourcesDirectory)
    Contents: |
     bin\$(BuildConfiguration)\**
    TargetFolder: $(Build.ArtifactStagingDirectory)\out

- task: PublishBuildArtifacts@1
  displayName: Publish build artifacts
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)\out
    ArtifactName: drop
    publishLocation: Container
