# Copyright (C) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license. See LICENSE.txt in the project root for license information.

variables:
  BuildConfiguration: Release
  SignType: real
  TeamName: vssetup

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md

pr: none

queue:
  name: VSEngSS-MicroBuild2019-1ES
  timeoutInMinutes: 120

steps:
- checkout: self
  fetchDepth: 0 # avoid shallow clone so nbgv can do its work.

- task: MicroBuildSigningPlugin@4
  inputs:
    signType: '$(SignType)'
    feedSource: 'https://devdiv.pkgs.visualstudio.com/DefaultCollection/_packaging/MicroBuildToolset/nuget/v3/index.json'
  env:
    TeamName: '$(TeamName)'

- template: build.yml
  parameters:
      BuildConfiguration: $(BuildConfiguration)